- name: Play with list vars
  hosts: all

  vars:
    named_list:
      - item1
      - item2
      - item3
      - item4

  tasks:
    - name: debug dic of lists
      debug:
        msg: "{{ named_list }}"
    
    - name: Take first element from list with dot notation
      debug:
        msg: "{{ named_list.0 }}"

    - name: Take the first element from list using python bracket notation
      debug:
        msg: "{{ named_list[0] }}"
